### PR TITLE
Adding pingbox.app link

### PR DESCRIPTION
**Pull request by TrevorJTClarke**

### CODE REVIEW

**Comment by zavodil** [comment]
Thank you for your contribution!
Why should we point at Pingbox among other NEAR applications? James wrote me today about it we didn't agree on the reasons.

**Comment by TrevorJTClarke** [comment]
@zavodil is there a better spot for it? Wasn't sure exactly where that makes sense.
The whole idea is to help promote user engagement with on-chain activity as much as possible. There's many things like sputnik that are getting missed.

**Comment by zavodil** [comment]
Its a great idea! 
I believe I'll add a link to the public directory like https://awesomenear.com/ to cover the whole ecosystem

**Comment by TrevorJTClarke** [comment]
Good idea @zavodil! I believe this would be a better spot: https://github.com/near/ecosystem as it is not a centralized entity with gated submissions.

**Pull request closed without merging**
